version: 2
jobs:
  build:
    working_directory: ~/project
    branches:
      only:
        - master
    docker:
      - image: circleci/clojure:boot-node
    steps:
      - run: sudo npm install -g npm@latest
      - checkout
      - restore_cache:
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: boot prod
      - store_artifacts:
          path: ~/project/target
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}
    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx4096m"
      BOOT_WATCHERS_DISABLE: "yes"